name: 'Semantic Release Notes Generator'
description: 'Generates release notes using semantic-release/release-notes-generator'
author: 'Fredrik Arvidsson'
inputs:
  owner:
    description: 'The Github user or organization that owns the repositories'
    required: true
  token:
    description: 'github token'
    required: false
  changes:
    description: 'A string representing all the updated images in "image: old_tag -> new_tag" format'
    required: true
outputs:
  release_notes:
    description: 'Semantic release notes'
runs:
  using: 'node12'
  main: 'main.js'
branding:
  icon: 'file-text'
  color: 'orange'
